### ISSUE TITLE
files are missing from client/resources/public directory

### ISSUE THREAD

**Issue by vamitrou** [FRosner/project-pia#21]
```
"GET /js/compiled/out/goog/base.js HTTP/1.1" 404 -
"GET /js/compiled/dev.js HTTP/1.1" 404 -
"GET /js/compiled/out/goog/base.js HTTP/1.1" 404 -
"GET /js/compiled/dev.js HTTP/1.1" 404 -
```

@Gerrrr what these files are and where can I fetch them from?

**Comment by Gerrrr** [comment]
This is a javascript code compiled from Clojurescript sources. You should run `lein cljsbuild once dev` inside `client` folder to generate them (Step 6 in the [Setup](https://github.com/FRosner/project-pia#setup) instruction).

**Comment by vamitrou** [comment]
nice, thanks!
